sequenceDiagram
  participant A
  participant B
  participant C
  participant E

  A->>B: dep10:00, arr10:30
  A->>B: d11:00,a11:30
  A->>B: d12:00,a12:30
  A->>B: d13:00,a13:30

  E->>C: d10:15,a10:45
  E->>C: d11:15,a11:45
  E->>C: d12:15,a12:45
  E->>C: d13:15,a13:45
